# Generated by Django 5.0.7 on 2024-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Status', models.CharField(default='pending...', max_length=10)),
            ],
        ),
    ]
